from fastapi import APIRouter

from trading import broker_service, research_service, trade_service

router = APIRouter(prefix="/api", tags=["trading"])

router.post("/trades/import-paste")(trade_service.import_trades_from_paste)
router.get("/trades/positions")(trade_service.list_trade_positions)
router.get("/trades")(trade_service.list_trades)
router.get("/trades/search-options")(trade_service.list_trade_search_options)
router.get("/trades/count")(trade_service.count_trades)
router.get("/trades/statistics")(trade_service.get_statistics)
router.get("/trades/analytics")(trade_service.get_trade_analytics)
router.post("/trades")(trade_service.create_trade)
router.get("/trades/{trade_id:int}")(trade_service.get_trade)
router.get("/trades/{trade_id:int}/risk-point-history")(trade_service.list_trade_risk_point_history)
router.put("/trades/{trade_id:int}")(trade_service.update_trade)
router.delete("/trades/{trade_id:int}")(trade_service.delete_trade)
router.get("/trades/sources")(trade_service.list_trade_sources)
router.get("/trades/symbols")(trade_service.list_trade_symbols)
router.get("/trade-review-taxonomy")(trade_service.get_trade_review_taxonomy)
router.get("/trades/{trade_id:int}/review")(trade_service.get_trade_review)
router.put("/trades/{trade_id:int}/review")(trade_service.upsert_trade_review)
router.delete("/trades/{trade_id:int}/review")(trade_service.delete_trade_review)
router.get("/trades/{trade_id:int}/source-metadata")(trade_service.get_trade_source_metadata)
router.put("/trades/{trade_id:int}/source-metadata")(trade_service.upsert_trade_source_metadata)
router.get("/trades/{trade_id:int}/linked-plans")(trade_service.get_trade_linked_plans)
router.get("/trades/research/folders")(research_service.list_research_folders)
router.post("/trades/research/folders")(research_service.create_research_folder)
router.put("/trades/research/folders/{folder_id:int}")(research_service.update_research_folder)
router.delete("/trades/research/folders/{folder_id:int}")(research_service.delete_research_folder)
router.get("/trades/research/documents")(research_service.list_research_documents)
router.post("/trades/research/documents")(research_service.create_research_document)
router.get("/trades/research/documents/{document_id:int}")(research_service.get_research_document)
router.put("/trades/research/documents/{document_id:int}")(research_service.update_research_document)
router.delete("/trades/research/documents/{document_id:int}")(research_service.delete_research_document)
router.get("/trades/research/recycle")(research_service.list_research_recycle)
router.post("/trades/research/recycle/{document_id:int}/restore")(research_service.restore_research_document)
router.delete("/trades/research/recycle/{document_id:int}/purge")(research_service.purge_research_document)
router.delete("/trades/research/recycle")(research_service.clear_research_recycle)
router.get("/trades/research/resolve-link")(research_service.resolve_research_link)
router.get("/trades/research/documents/{document_id:int}/backlinks")(research_service.list_research_backlinks)
router.get("/trade-brokers")(broker_service.list_trade_brokers)
router.post("/trade-brokers")(broker_service.create_trade_broker)
router.put("/trade-brokers/{broker_id}")(broker_service.update_trade_broker)
router.delete("/trade-brokers/{broker_id}")(broker_service.delete_trade_broker)
